#!/bin/sh
#
#  mkf - make a file from the pipe and execute command
#  Copyright (C) 2019 Zhang Maiyun <me@maiyun.me>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

tf="$(mktemp tmp-mkf.XXXX)"

cat > "$tf"

if [ "$*" = "" ]; then
    cat "$tf"
    rm "$tf"
    exit 1
fi

# Whitespace for $* is intended
# shellcheck disable=SC2048
$* "$tf"
ret="$?"

rm "$tf"
exit "$ret"
