[package]
name = "part_on_demand"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4"
ureq = "2.2"
zstd = "0.9"
