[package]
name = "mkf"
version = "0.2.2"
authors = ["Zhang Maiyun <myzhang1029@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["cargo"] }
tempfile = "3.3.0"
